# Setup
title: Lab 6
remote_theme: poole/lanyon
tagline: Bedrock Chatbot
description:
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Grace Wang
  email: gw101@wellesley.edu

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y

